<?php

/**
 * Shared category language. This is data, not publication-specific code.
 * Unknown homepage categories are still compiled from their own manifest
 * label, description, slug and Elementor section evidence.
 */
return [
    'aliases' => [
        'pharmaceutical' => 'pharma',
        'pharmaceuticals' => 'pharma',
    ],
    'generic_sections' => [
        'news', 'breaking news', 'trending', 'features', 'industry updates',
        'industry trends', 'industry commentary', 'resources', 'guides',
        'tutorials', 'how to', 'expert roundups', 'press release',
        'press releases', 'international', 'viral news', 'knowledge base',
        'from the ground up',
    ],
    'evergreen_sections' => ['knowledge base', 'resources', 'guides', 'tutorials', 'how to'],
    'stop_words' => [
        'a', 'an', 'and', 'article', 'articles', 'at', 'by', 'for', 'from',
        'in', 'into', 'news', 'of', 'on', 'or', 'the', 'to', 'with',
    ],
    'vocabulary' => [
        'business' => ['business', 'companies', 'economy', 'earnings', 'acquisition', 'interest rates', 'inflation', 'federal reserve', 'markets', 'revenue', 'profit'],
        'business and industry' => ['business', 'companies', 'industry', 'earnings', 'acquisition'],
        'science and innovation' => ['science', 'scientific research', 'research breakthrough', 'innovation', 'applied research'],
        'infrastructure' => ['infrastructure', 'infrastructure investment', 'public works', 'critical infrastructure', 'digital infrastructure'],
        'quantum computing' => ['quantum computing', 'quantum computer', 'qubits', 'quantum processor', 'quantum technology'],
        'entrepreneur' => ['entrepreneur', 'entrepreneurs', 'startup', 'founder', 'venture capital'],
        'entrepreneurs' => ['entrepreneur', 'entrepreneurs', 'startup', 'founder', 'venture capital'],
        'entrepreneurship' => ['entrepreneurship', 'startup', 'founder', 'small business', 'venture capital'],
        'startup' => ['startup', 'startups', 'founder', 'founders', 'venture capital', 'funding round', 'early stage company', 'new venture'],
        'celebrity' => ['celebrity', 'actor', 'actress', 'singer', 'Hollywood'],
        'fashion' => ['fashion', 'designer', 'apparel', 'runway', 'fashion week'],
        'lifestyle' => ['lifestyle', 'wellness', 'food', 'home design', 'culture'],
        'luxury' => ['luxury', 'luxury brands', 'yachts', 'luxury hotels', 'luxury cars'],
        'politics' => ['politics', 'election', 'government', 'legislation', 'Congress', 'governor', 'legislature', 'legislator', 'lawmakers', 'public policy', 'state budget', 'government spending', 'public funds'],
        'real estate' => ['real estate', 'housing', 'property market', 'mortgage', 'commercial property'],
        'travel' => ['travel', 'tourism', 'airlines', 'hotels', 'destinations'],
        'technology' => ['technology', 'software', 'artificial intelligence', 'semiconductor', 'cybersecurity'],
        'tech' => ['technology', 'software', 'artificial intelligence', 'semiconductor', 'cybersecurity'],
        'ai' => ['artificial intelligence', 'machine learning', 'AI models', 'AI chips', 'AI regulation'],
        'robotics' => ['robotics', 'robots', 'industrial automation', 'autonomous robots', 'robot engineering'],
        'automation' => ['automation', 'automated systems', 'robotic systems', 'workflow automation', 'autonomous systems'],
        'medical' => ['medical research', 'healthcare', 'clinical research', 'patient care', 'public health'],
        'biotech' => ['biotechnology', 'biotech research', 'biopharmaceutical', 'cell therapy', 'gene therapy'],
        'pharma' => ['pharmaceutical', 'pharmaceuticals', 'pharma', 'drug development', 'clinical trial', 'clinical trials', 'drug approval', 'pharmaceutical research', 'biopharmaceutical', 'therapeutic', 'therapy', 'cell therapy', 'gene therapy', 'medicine', 'medicines'],
        'podcasts' => ['podcast interview', 'podcast episode', 'podcast conversation', 'audio interview'],
        'innovation' => ['innovation', 'applied research', 'research breakthrough', 'new technology', 'scientific discovery'],
        'personal tech' => ['personal technology', 'consumer technology', 'smartphone', 'personal computing', 'consumer electronics'],
        'smart home' => ['smart home', 'home automation', 'connected home', 'smart appliances', 'home security technology'],
        'wearable devices' => ['wearable devices', 'wearable technology', 'smartwatch', 'smart glasses', 'fitness tracker'],
        'health tech' => ['health technology', 'medical technology', 'digital health', 'medical devices', 'healthcare software'],
        'cybersecurity' => ['cybersecurity', 'cyber security', 'data breach', 'ransomware', 'network security'],
        'data privacy' => ['data privacy', 'data protection', 'privacy regulation', 'personal data', 'digital privacy'],
        'innovations' => ['innovation', 'emerging technology', 'applied research', 'new technology', 'research breakthrough'],
        'finance' => ['finance', 'markets', 'banking', 'investing', 'interest rates'],
        'consumer' => ['consumer products', 'retail', 'consumer spending', 'shopping', 'consumer technology'],
        'clean energy' => ['clean energy', 'renewable energy', 'solar power', 'wind power', 'energy storage'],
        'gadgets and apps' => ['gadgets', 'mobile apps', 'smartphone', 'consumer electronics', 'software'],
        'e-commerce' => ['ecommerce', 'online retail', 'online shopping', 'retail technology', 'digital commerce'],
        'leadership' => ['business leadership', 'management', 'executive', 'workplace', 'company strategy'],
        'reputation management' => ['reputation management', 'corporate reputation', 'public relations', 'brand reputation', 'crisis communications'],
        'business law' => ['business law', 'corporate law', 'commercial law', 'regulation', 'regulatory', 'compliance', 'antitrust', 'litigation', 'lawsuit', 'legal', 'court ruling', 'corporate governance', 'contract law', 'merger review'],
        'law' => ['law', 'legal', 'regulation', 'lawsuit', 'litigation', 'court ruling', 'legislation', 'attorney', 'lawyer', 'judge', 'compliance'],
        'legal' => ['law', 'regulation', 'lawsuit', 'legal services', 'court ruling'],
        'personal development' => ['career development', 'professional skills', 'learning', 'mentoring', 'productivity'],
        'diversity' => ['workplace diversity', 'inclusion', 'equal opportunity', 'accessibility', 'representation'],
        'women entrepreneurs' => ['women entrepreneurs', 'women founders', 'female founders', 'women owned business', 'women startup leaders'],
        'personal finance' => ['personal finance', 'saving', 'budgeting', 'retirement planning', 'consumer credit'],
        'podcasts and shows' => ['podcast', 'audio series', 'interview', 'business show', 'digital media'],
        'startup show podcast' => ['startup podcast', 'founder interview', 'entrepreneur interview', 'business podcast', 'startup show'],
        'banking and lending' => ['banking', 'lending', 'banks', 'credit', 'loans'],
        'wealth management and investing' => ['wealth management', 'investing', 'investment', 'asset management', 'portfolio management'],
        'digital payments' => ['digital payments', 'payment technology', 'mobile payments', 'payment processing', 'digital wallets'],
        'emerging tech' => ['emerging technology', 'artificial intelligence', 'software', 'automation', 'cybersecurity'],
        'fintech' => ['fintech', 'financial technology', 'digital banking', 'payment technology', 'digital finance'],
        'sports' => ['sports', 'football', 'basketball', 'tennis', 'athletics'],
        'music' => ['music', 'musicians', 'concert', 'album', 'recording industry'],
        'entertainment' => ['entertainment', 'film', 'television', 'streaming', 'box office'],
        'health' => ['health', 'medicine', 'clinical trial', 'public health', 'medical research'],
        'mental health' => ['mental health', 'psychiatry', 'psychological care', 'behavioral health', 'mental illness'],
        'aging' => ['healthy aging', 'aging research', 'biological age', 'age related disease', 'geroscience'],
        'longevity basics' => ['longevity', 'healthy aging', 'healthspan', 'aging research', 'geroscience'],
        'wellness' => ['wellness', 'preventive health', 'sleep health', 'nutrition', 'physical activity'],
        'cryptocurrency' => ['cryptocurrency', 'bitcoin', 'ethereum', 'crypto regulation', 'digital assets'],
        'crypto' => ['cryptocurrency', 'bitcoin', 'ethereum', 'crypto regulation', 'digital assets'],
        'bitcoin' => ['bitcoin', 'BTC', 'bitcoin mining', 'bitcoin ETF', 'bitcoin network'],
        'polygon' => ['Polygon blockchain', 'Polygon network', 'Polygon crypto', 'Polygon ecosystem', 'POL token'],
        'nft' => ['NFT', 'non fungible tokens', 'digital collectibles', 'NFT marketplace', 'tokenized art'],
        'blockchain' => ['blockchain', 'tokenization', 'decentralized finance', 'Web3', 'digital assets'],
        'public relations' => ['public relations', 'press release distribution', 'corporate communications', 'media relations', 'PR agencies'],
        'vehicle tech' => ['electric vehicle', 'autonomous vehicle', 'automotive', 'vehicle technology', 'vehicle safety'],
        'smart infrastructure' => ['smart infrastructure', 'smart cities', 'smart building', 'intelligent transport', 'building automation'],
        'travel tech' => ['travel technology', 'travel booking', 'airline', 'airport', 'tourism technology'],
        'green transit' => ['public transit', 'electric bus', 'sustainable transport', 'rail electrification', 'zero emission vehicle'],
        'transportation news' => ['transportation', 'transit', 'railway', 'airline', 'freight'],
    ],
];
